[project]
name = "class"
version = "0.1.0"
description = ""
authors = [
    {name = "Roman Siyanko",email = "romasi98@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest (>=8.3.5,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.lint.dependencies]
flake8 = "^7.1.2"
black = "^25.1.0"
isort = "^6.0.1"
mypy = "^1.15.0"

[tool.poetry]
packages = [{ include = "src" }]
name = "classcomputer22222"
version = "0.1.0"
description = "classes"
authors = ["Roman <romasi98@mail.ru>"]
